-- Write your PostgreSQL query statement below
SELECT PROJECT_ID, ROUND(AVG(EXPERIENCE_YEARS),2) AS AVERAGE_YEARS
FROM PROJECT 
INNER JOIN EMPLOYEE 
ON PROJECT.EMPLOYEE_ID=EMPLOYEE.EMPLOYEE_ID
GROUP BY PROJECT_ID;